language : python
sudo: required
python:
    - "3.4"
before_install:
    - sudo apt-get update
    - sudo apt-get upgrade
    - sudo apt-get install cmake
    - git clone https://github.com/lloyd/yajl.git
    - cd yajl
    - sudo ./configure
    - sudo make install
    - cd ..
install:
    - pip install again
    - pip install pytest
script: sudo py.test
